# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2


class FetchStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Capitalize = channel.unary_unary(
        '/rpc.Fetch/Capitalize',
        request_serializer=message__pb2.Payload.SerializeToString,
        response_deserializer=message__pb2.Payload.FromString,
        )


class FetchServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Capitalize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FetchServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Capitalize': grpc.unary_unary_rpc_method_handler(
          servicer.Capitalize,
          request_deserializer=message__pb2.Payload.FromString,
          response_serializer=message__pb2.Payload.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rpc.Fetch', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
